version: "3"

networks:
  internal:
    external: false

# before you run "docker-compose up" set SECRET_KEY_BASE !
services:
  app:
    image: video
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_INSTANCE=postgres
      - DB_HOST=db
    ports:
      - 4000:4000
    networks:
      - internal
    depends_on:
      - db
# The db container creates the data/db file as root! (sudo rm -r data/) to remove it!
  db:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - internal
